ms:
  means:
  #- 1794.311
  - 1925.161
  - 2183.128
  - 2338.041
  - 2667.254
  - 3233.633
  - 3460.96
  - 3555.569
  - 3619.542
  #- 3703.298
  - 3406.497
  - 2841.645
  stds:
  #- 1164.883
  - 1205.586
  - 1223.713
  - 1399.638
  - 1403.298
  - 1378.513
  - 1434.924
  - 1491.141
  - 1454.089
  #- 1660.395
  - 1473.248
  - 1365.08
  size:
  - 224
rgb:
  means:
  - 0.48145466
  - 0.4578275
  - 0.40821073
  stds:
  - 0.26862954
  - 0.26130258
  - 0.27577711
  size:
  - 224

ms_all:
  means:
  - 1794.311
  - 1925.161
  - 2183.128
  - 2338.041
  - 2667.254
  - 3233.633
  - 3460.96
  - 3555.569
  - 3619.542
  - 3703.298
  - 3406.497
  - 2841.645
  stds:
  - 1164.883
  - 1205.586
  - 1223.713
  - 1399.638
  - 1403.298
  - 1378.513
  - 1434.924
  - 1491.141
  - 1454.089
  - 1660.395
  - 1473.248
  - 1365.08
  size:
  - 224

